/**
 * FacturX / ZUGFeRD metadata stub
 * ─────────────────────────────────────────────────────────────────────────────
 * FacturX is a hybrid PDF/XML standard (EN 16931 / FNFE-MPE) required by the
 * 2026-2027 French e-invoicing reform.  A FacturX document is a standard PDF
 * that embeds a machine-readable XML attachment following the Cross Industry
 * Invoice (CII) UN/CEFACT schema.
 *
 * This module:
 *   1. Defines the TypeScript shape of the data needed for the XML
 *   2. Generates a MINIMUM conformance-level CII XML string (MINIMUM profile)
 *      — enough to satisfy the legal archival requirement for quotes.
 *   3. Can be upgraded to BASIC or EN-16931 profiles when full e-invoicing
 *      is required (invoices, not just quotes).
 *
 * Current status: QUOTE (Devis) — not yet a legal invoice.
 * The XML generated here is a forward-compatible metadata snapshot.
 */

export interface FacturXSeller {
  name: string;
  siret: string;
  tvaIntra?: string;
  address: string;
  postalCode: string;
  city: string;
  country?: string; // default "FR"
}

export interface FacturXBuyer {
  name: string;
  address?: string;
  email?: string;
}

export interface FacturXLine {
  id: number;
  description: string;
  quantity: number;
  unitPrice: number;        // HT
  tvaTaux: number;          // e.g. 20
  lineTotal: number;        // quantity × unitPrice HT
}

export interface FacturXTotals {
  totalHTBrut: number;
  remise: number;
  totalHT: number;
  totalTVA: number;
  totalTTC: number;
  acompte?: number;
}

export interface FacturXDocument {
  documentType: 'DEVIS' | 'FACTURE';
  documentNumber: string;
  issueDate: string;        // ISO 8601  e.g. "2026-04-04"
  dueDate?: string;
  seller: FacturXSeller;
  buyer: FacturXBuyer;
  lines: FacturXLine[];
  totals: FacturXTotals;
  currency?: string;        // default "EUR"
  notes?: string;
}

/**
 * Generates an EN 16931 / FacturX MINIMUM profile CII XML string.
 * Embed this as "factur-x.xml" inside the final PDF to be FacturX ready.
 */
export function genererFacturXXML(doc: FacturXDocument): string {
  const esc = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

  const fmt2 = (n: number) => n.toFixed(2);
  const currency = doc.currency ?? 'EUR';
  const country = doc.seller.country ?? 'FR';

  // Group TVA by rate for the tax summary
  const tvaByRate: Record<number, number> = {};
  doc.lines.forEach(l => {
    tvaByRate[l.tvaTaux] = (tvaByRate[l.tvaTaux] ?? 0) + l.lineTotal * (l.tvaTaux / 100);
  });

  const taxTotalsXML = Object.entries(tvaByRate)
    .map(
      ([rate, amount]) => `
    <ram:ApplicableTradeTax>
      <ram:CalculatedAmount>${fmt2(amount)}</ram:CalculatedAmount>
      <ram:TypeCode>VAT</ram:TypeCode>
      <ram:BasisAmount>${fmt2(doc.totals.totalHT)}</ram:BasisAmount>
      <ram:CategoryCode>S</ram:CategoryCode>
      <ram:RateApplicablePercent>${rate}</ram:RateApplicablePercent>
    </ram:ApplicableTradeTax>`
    )
    .join('');

  const linesXML = doc.lines
    .map(
      (l, i) => `
  <ram:IncludedSupplyChainTradeLineItem>
    <ram:AssociatedDocumentLineDocument>
      <ram:LineID>${i + 1}</ram:LineID>
    </ram:AssociatedDocumentLineDocument>
    <ram:SpecifiedTradeProduct>
      <ram:Name>${esc(l.description)}</ram:Name>
    </ram:SpecifiedTradeProduct>
    <ram:SpecifiedLineTradeAgreement>
      <ram:NetPriceProductTradePrice>
        <ram:ChargeAmount>${fmt2(l.unitPrice)}</ram:ChargeAmount>
      </ram:NetPriceProductTradePrice>
    </ram:SpecifiedLineTradeAgreement>
    <ram:SpecifiedLineTradeDelivery>
      <ram:BilledQuantity unitCode="C62">${l.quantity}</ram:BilledQuantity>
    </ram:SpecifiedLineTradeDelivery>
    <ram:SpecifiedLineTradeSettlement>
      <ram:ApplicableTradeTax>
        <ram:TypeCode>VAT</ram:TypeCode>
        <ram:CategoryCode>S</ram:CategoryCode>
        <ram:RateApplicablePercent>${l.tvaTaux}</ram:RateApplicablePercent>
      </ram:ApplicableTradeTax>
      <ram:SpecifiedTradeSettlementLineMonetarySummation>
        <ram:LineTotalAmount>${fmt2(l.lineTotal)}</ram:LineTotalAmount>
      </ram:SpecifiedTradeSettlementLineMonetarySummation>
    </ram:SpecifiedLineTradeSettlement>
  </ram:IncludedSupplyChainTradeLineItem>`
    )
    .join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- FacturX MINIMUM profile — generated by DevisPro -->
<!-- Document type: ${doc.documentType} — NOT a legal invoice -->
<rsm:CrossIndustryInvoice
  xmlns:rsm="urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100"
  xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100"
  xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100">

  <rsm:ExchangedDocumentContext>
    <ram:GuidelineSpecifiedDocumentContextParameter>
      <ram:ID>urn:factur-x.eu:1p0:minimum</ram:ID>
    </ram:GuidelineSpecifiedDocumentContextParameter>
  </rsm:ExchangedDocumentContext>

  <rsm:ExchangedDocument>
    <ram:ID>${esc(doc.documentNumber)}</ram:ID>
    <ram:TypeCode>${doc.documentType === 'FACTURE' ? '380' : '916'}</ram:TypeCode>
    <ram:IssueDateTime>
      <udt:DateTimeString format="102">${doc.issueDate.replace(/-/g, '')}</udt:DateTimeString>
    </ram:IssueDateTime>
    ${doc.notes ? `<ram:IncludedNote><ram:Content>${esc(doc.notes)}</ram:Content></ram:IncludedNote>` : ''}
  </rsm:ExchangedDocument>

  <rsm:SupplyChainTradeTransaction>

    ${linesXML}

    <ram:ApplicableHeaderTradeAgreement>
      <ram:SellerTradeParty>
        <ram:Name>${esc(doc.seller.name)}</ram:Name>
        <ram:SpecifiedLegalOrganization>
          <ram:ID schemeID="0009">${esc(doc.seller.siret)}</ram:ID>
        </ram:SpecifiedLegalOrganization>
        ${doc.seller.tvaIntra ? `<ram:SpecifiedTaxRegistration><ram:ID schemeID="VA">${esc(doc.seller.tvaIntra)}</ram:ID></ram:SpecifiedTaxRegistration>` : ''}
        <ram:PostalTradeAddress>
          <ram:PostcodeCode>${esc(doc.seller.postalCode)}</ram:PostcodeCode>
          <ram:LineOne>${esc(doc.seller.address)}</ram:LineOne>
          <ram:CityName>${esc(doc.seller.city)}</ram:CityName>
          <ram:CountryID>${esc(country)}</ram:CountryID>
        </ram:PostalTradeAddress>
      </ram:SellerTradeParty>
      <ram:BuyerTradeParty>
        <ram:Name>${esc(doc.buyer.name)}</ram:Name>
      </ram:BuyerTradeParty>
    </ram:ApplicableHeaderTradeAgreement>

    <ram:ApplicableHeaderTradeDelivery />

    <ram:ApplicableHeaderTradeSettlement>
      <ram:InvoiceCurrencyCode>${currency}</ram:InvoiceCurrencyCode>
      ${taxTotalsXML}
      <ram:SpecifiedTradeSettlementHeaderMonetarySummation>
        <ram:LineTotalAmount>${fmt2(doc.totals.totalHTBrut)}</ram:LineTotalAmount>
        <ram:AllowanceTotalAmount>${fmt2(doc.totals.remise)}</ram:AllowanceTotalAmount>
        <ram:TaxBasisTotalAmount>${fmt2(doc.totals.totalHT)}</ram:TaxBasisTotalAmount>
        <ram:TaxTotalAmount currencyID="${currency}">${fmt2(doc.totals.totalTVA)}</ram:TaxTotalAmount>
        <ram:GrandTotalAmount>${fmt2(doc.totals.totalTTC)}</ram:GrandTotalAmount>
        <ram:DuePayableAmount>${fmt2(doc.totals.totalTTC)}</ram:DuePayableAmount>
      </ram:SpecifiedTradeSettlementHeaderMonetarySummation>
    </ram:ApplicableHeaderTradeSettlement>

  </rsm:SupplyChainTradeTransaction>

</rsm:CrossIndustryInvoice>`;
}
